# Generated by Django 4.1.6 on 2023-02-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=13)),
                ("content", models.TextField()),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
