# Generated by Django 4.1.6 on 2023-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=13)),
                ("timeStamp", models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(name="Contact",),
    ]
