# Generated by Django 4.1.4 on 2023-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="views", field=models.IntegerField(default=0),
        ),
    ]
